export const PHP_FILE_HEADER = [
  "/**",
  " * +------------------------------------------------------------+",
  " * |                        DO NOT EDIT                         |",
  " * |      Generated by Skir. Changes will be overwritten.       |",
  " * +------------------------------------------------------------+",
  " */",
].join("\n");
