export interface PhpFileInput {
  readonly namespace: string;
  readonly imports: readonly string[];
  readonly body: string;
}

export const PHP_FILE_HEADER = [
  "/**",
  " * +------------------------------------------------------------+",
  " * |                        DO NOT EDIT                         |",
  " * |      Generated by Skir. Changes will be overwritten.       |",
  " * +------------------------------------------------------------+",
  " */",
].join("\n");

export function indent(code: string): string {
  return code
    .split("\n")
    .map((line) => (line === "" ? line : `    ${line}`))
    .join("\n");
}

export function renderPhpFile(input: PhpFileInput): string {
  return [
    "<?php",
    "",
    "declare(strict_types=1);",
    "",
    PHP_FILE_HEADER,
    "",
    `namespace ${input.namespace};`,
    ...(input.imports.length === 0 ? [] : ["", ...input.imports]),
    "",
    ...(input.body === "" ? [] : [input.body]),
    "",
  ].join("\n");
}
